;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        c-electric-delete-forward
        c-electric-paren
        c-electric-semi&comma
        c-end-of-statement
        select-word-and-expand
        select-word-and-next
        smex
        yas-expand
        ))

(setq mc/cmds-to-run-once
      '(
        c-electric-colon
        c-electric-star
        isearch-repeat-forward
        list-directory
        mouse-buffer-menu
        mouse-set-region
        next-multiframe-window
        ))
